/** @type {import('tailwindcss').Config} */
module.exports = {
  corePlugins: {
    preflight: false, // Docusaurus has its own preflight, but let's disable tailwind's to avoid conflicts
  },
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./docs/**/*.mdx"],
  darkMode: ["class", '[data-theme="dark"]'], // Support Docusaurus dark mode toggle
  theme: {
    extend: {
        colors: {
            "background": "#fcf9f8",
            "border-muted": "#E5E9F0",
            "error": "#ba1a1a",
            "error-container": "#ffdad6",
            "inverse-on-surface": "#f3f0ef",
            "inverse-primary": "#aec6ff",
            "inverse-surface": "#303030",
            "on-background": "#1b1b1b",
            "on-error": "#ffffff",
            "on-error-container": "#93000a",
            "on-primary": "#ffffff",
            "on-primary-container": "#fefcff",
            "on-primary-fixed": "#001a42",
            "on-primary-fixed-variant": "#004396",
            "on-secondary": "#ffffff",
            "on-secondary-container": "#56657b",
            "on-secondary-fixed": "#0c1c2f",
            "on-secondary-fixed-variant": "#39485c",
            "on-surface": "#1b1b1b",
            "on-surface-variant": "#424754",
            "on-tertiary": "#ffffff",
            "on-tertiary-container": "#fffbff",
            "on-tertiary-fixed": "#311300",
            "on-tertiary-fixed-variant": "#733500",
            "outline": "#727785",
            "outline-variant": "#c2c6d6",
            "primary": "#0058bf",
            "primary-container": "#1470ea",
            "primary-fixed": "#d8e2ff",
            "primary-fixed-dim": "#aec6ff",
            "secondary": "#515f75",
            "secondary-container": "#d4e3fd",
            "secondary-fixed": "#d4e3fd",
            "secondary-fixed-dim": "#b8c7e0",
            "status-danger": "#EF4444",
            "status-info": "#3884FF",
            "status-success": "#10B981",
            "status-warning": "#F59E0B",
            "surface": "#fcf9f8",
            "surface-subtle": "#F6FAFF",
            "surface-bright": "#fcf9f8",
            "surface-container": "#f0eded",
            "surface-container-high": "#eae7e7",
            "surface-container-highest": "#e5e2e1",
            "surface-container-low": "#f6f3f2",
            "surface-container-lowest": "#ffffff",
            "surface-dim": "#dcd9d9",
            "surface-tint": "#005ac3",
            "surface-variant": "#e5e2e1",
            "tertiary": "#944600",
            "tertiary-container": "#ba5900",
            "tertiary-fixed": "#ffdbc8",
            "tertiary-fixed-dim": "#ffb689",
            "sidebar-bg": "#f0eded"
        },
        borderRadius: {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px"
        },
        spacing: {
            "sidebar-width": "280px",
            "gutter": "1.5rem",
            "content-width-max": "800px",
            "page-margin": "2rem",
            "section-gap": "3rem"
        },
        fontFamily: {
            "label-caps": ["Inter", "sans-serif"],
            "headline-lg": ["Manrope", "sans-serif"],
            "body-sm": ["Inter", "sans-serif"],
            "body-md": ["Inter", "sans-serif"],
            "code-block": ["JetBrains Mono", "monospace"],
            "headline-xl-mobile": ["Manrope", "sans-serif"],
            "headline-xl": ["Manrope", "sans-serif"],
            "body-lg": ["Inter", "sans-serif"],
            "headline-md": ["Manrope", "sans-serif"]
        },
        fontSize: {
            "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
            "headline-lg": ["30px", { "lineHeight": "36px", "fontWeight": "600" }],
            "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
            "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
            "code-block": ["14px", { "lineHeight": "22px", "fontWeight": "400" }],
            "headline-xl-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
            "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
            "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
            "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
        }
    },
  },
  plugins: [],
}
